---
- hosts: all
  #remote_user: root
  become: yes
  become_method: sudo
  pre_tasks:
      - name: 'install python2'
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        when: "ansible_distribution == 'Ubuntu'"
  roles:
     - { role: nginx-custom, tags: ['install', 'deploy']}
